name: Generate Tag

on:
  push:
    branches:
      - main

jobs:
  create_tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Get current version
      id: get_version
      run: |
        if [ -f version.txt ]; then
          version=$(cat version.txt)
          echo "Current version: $version"
        else
          version=0.0.0
          echo "0.0.0" > version.txt
          echo "Current version: $version"
        fi
        echo "::set-output name=version::$version"

    - name: Increment version
      id: increment_version
      run: |
        version=${{ steps.get_version.outputs.version }}
        IFS='.' read -r major minor patch <<< "$version"
        patch=$((patch + 1))
        new_version="$major.$minor.$patch"
        echo "New version: $new_version"
        echo "::set-output name=new_version::$new_version"
        echo $new_version > version.txt

    - name: Commit new version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add version.txt
        git commit -m "chore: bump version to ${{ steps.increment_version.outputs.new_version }}"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/kantikorn/Project_helloworld.git HEAD:main

    - name: Create new tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git tag v${{ steps.increment_version.outputs.new_version }}
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/kantikorn/Project_helloworld.git v${{ steps.increment_version.outputs.new_version }}
