name: Generate Tag

on:
  push:
    branches:
      - main

jobs:
  test_and_create_tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Check loop condition
      if: success()
      run: |
        version=$(cat version.txt)
        if [ "$version" -gt 10 ]; then
          echo "Error: Loop condition exceeded (greater than 10). Please fix before committing."
          exit 1
        fi

    - name: Set up Git
      if: success()
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

        # Commit new version and push
        git add version.txt
        git commit -m "chore: bump version to ${{ steps.increment_version.outputs.new_version }}"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/kantikorn/Project_helloworld.git HEAD:main

    - name: Create new tag
      if: success()
      run: |
        # Tag the new version and push
        git tag v${{ steps.increment_version.outputs.new_version }}
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/kantikorn/Project_helloworld.git v${{ steps.increment_version.outputs.new_version }}
